# Generated by Django 4.1.3 on 2022-12-21 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=50)),
                ('Precio', models.PositiveIntegerField()),
                ('Stock', models.PositiveIntegerField()),
                ('Material', models.CharField(max_length=50)),
                ('Alto', models.PositiveIntegerField()),
                ('Ancho', models.PositiveIntegerField()),
                ('Largo', models.PositiveIntegerField()),
                ('Imagen_1', models.FileField(upload_to='static/images/productos/')),
                ('Imagen_2', models.FileField(upload_to='static/images/productos/')),
                ('Imagen_3', models.FileField(upload_to='static/images/productos/')),
                ('Imagen_4', models.FileField(upload_to='static/images/productos/')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Apellido', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Numero_Contacto', models.IntegerField()),
                ('Asunto', models.CharField(max_length=256)),
                ('Contenido_Mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Apellido', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Numero_Contacto', models.IntegerField()),
                ('Nombre_Proyecto', models.CharField(max_length=256)),
                ('Material', models.CharField(max_length=50)),
                ('Alto', models.PositiveIntegerField()),
                ('Ancho', models.PositiveIntegerField()),
                ('Largo', models.PositiveIntegerField()),
                ('Descripcion', models.TextField()),
                ('Archivo_Complementario_1', models.FileField(upload_to='static/docs/')),
                ('Archivo_Complementario_2', models.FileField(upload_to='static/docs/')),
                ('Archivo_Complementario_3', models.FileField(upload_to='static/docs/')),
                ('Archivo_Complementario_4', models.FileField(upload_to='static/docs/')),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_Productos', models.PositiveIntegerField()),
                ('Total', models.PositiveIntegerField()),
                ('Fecha', models.DateField()),
                ('Nombre_cliente', models.CharField(max_length=50)),
                ('Rut', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=256)),
                ('id_Producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.producto')),
                ('id_diseño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.solicitud_diseño')),
            ],
        ),
        migrations.CreateModel(
            name='producto_promocionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.producto')),
            ],
        ),
    ]
