# Generated by Django 4.1.3 on 2022-12-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Comprador', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Rut', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Producto', models.CharField(max_length=50)),
                ('Precio', models.PositiveIntegerField()),
                ('Stock', models.PositiveIntegerField()),
                ('Alto', models.PositiveIntegerField()),
                ('Ancho', models.PositiveIntegerField()),
                ('Largo', models.PositiveIntegerField()),
                ('Fabricado', models.BooleanField(verbose_name='A pedido')),
                ('Promocionado', models.BooleanField(default=False, verbose_name='Â¿Promocionar?')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_Productos', models.PositiveIntegerField(verbose_name='Productos Vendidos')),
                ('Total', models.PositiveIntegerField()),
                ('Fecha', models.DateField()),
                ('Pagado', models.BooleanField(default=False)),
                ('id_Comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.comprador', verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Registro de venta',
                'verbose_name_plural': 'Registros de venta',
            },
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ruta', models.ImageField(upload_to='static/images/')),
                ('Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='TiendaMueblesApp.producto')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.producto', verbose_name='Producto')),
                ('id_registro_Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.registro_venta')),
            ],
            options={
                'verbose_name': 'detalle de la venta',
                'verbose_name_plural': 'Detalles de las ventas',
            },
        ),
    ]
