# Generated by Django 4.1.2 on 2022-12-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMueblesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_promocionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMueblesApp.imagen')),
            ],
        ),
    ]
